### ISSUE TITLE
Testing: Review related updates

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#1019]
Changes in #1018 and  #1015 

- Disable Review criteria changes once a completed review has been submitted.
- Fix formatting criteria review listing on Panel view (/grants/[name]/panel) page and admin Submission Reviews (/grant/[name]/submissoins/[id]/reviews) page.

**Comment by lmkw** [comment]
@jseraf are these on staging, should I test there?

**Comment by jseraf** [comment]
@lmkw yes. i'll only open `testing` tickets when the work is on staging.

**Comment by lmkw** [comment]
@jseraf  #1015 looks great to me. 
for #1018, is this referring to the score next to the reviewer's name in the exported .pdf of all reviews? 
If so, the way it looks on production is a bit easier to read
<img width="539" alt="Screenshot 2023-09-29 at 4 08 17 PM" src="https://github.com/NUARIG/competitions/assets/12861678/ea974032-c986-4ce5-8bf9-1a1647496515">


vs. staging
<img width="495" alt="Screenshot 2023-09-29 at 4 08 52 PM" src="https://github.com/NUARIG/competitions/assets/12861678/6b67cbb6-fe45-4f95-b626-87ed46791bbe">

**Comment by jseraf** [comment]
PDF layout problem may be related to https://github.com/mileszs/wicked_pdf/issues/1041

**Comment by jseraf** [comment]
Changes deployed
