### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#119]
Fill out information? Laura will check in with Firas; E.g., prioritize title and eRA commons?
Currently have biosketch and everything from LDAP
From UNA get given name, friendly name, email address

Displays grants they've submitted, grants they review

**Comment by firaswehbe** [comment]
Three pages
---------

## Profile button next to log out button

* First Name (Greyed out)
* Last Name (Greyed out)
* Email (Greyed out)

* Unique ID (Greyed out)
* Role (greyed out) on of {user|grant creator|system admin} with a button to request "Grant Creator" Role

## Submission for to request grant creator role
* Show their First name, last name, email
* Note box with the reasons they are requesting 

The form should re-route to the profile page, the button would be greyed out and says "Grant Creater Role requested" or something to that effect. When routing the first time, put a vanishing banner that says "Your request has been submitted for review" a system administrator will let you know once that has been approved.

## If the session is for a system admin, there is a button next to sign out called "Admin page"

Admin page for now has a list in descending order of all requests to become grant creators with their status (approved or not)

**Comment by jseraf** [comment]
Partially completed in #151 

Moved request form to #152
