### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#125]
Needs user-friendly language to tell people:

What went wrong (generally, don't need to be technical. Can even say "Something went wrong")
What to do about it (again, generally. Can be "Try reloading the page" or "Try again later" or a link to retry)

**Comment by lmkw** [comment]
Create a user-friendly message to display when there are errors

**Comment by lmkw** [comment]
This page isn't available.
The link you followed may be broken or the page may have been removed. Please go to the home page. 

I got the text from here:
https://medium.com/ruby-on-rails-web-application-development/custom-400-500-error-pages-in-ruby-on-rails-exception-handler-3a04975e4677
