### ISSUE TITLE
UNA configuration for NCATS staging server

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#127]
Have Su talk to Amit, etc
Give them server information (name, certificates, etc)
#128 

Laura will give the following to Amit:

- IP address range to be whitelisted on CD2H cloud account for competitions application

- contact details (first and last name and email addresses) for who must have AWS console access

- contact details (first and last name and email addresses) for who must have SSH access to the EC2 instance to deploy applications

- contact details (first and last name and email addresses) for who must have access to create/update support tickets on NCATS service desk

Look up what Keats & Su asked of us re: UNA configuration, give that to Amit

**Comment by firaswehbe** [comment]
Requires that NCATS staging  are provisioned early on in this sprint
