### ISSUE TITLE
remove old grants from seed file

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#146]
Remove all but one grant from seed file. 

There will also need to be changes to incorporate /app/controllers/grants_controller.rb:42
    result = GrantServices::New.call(grant: @grant, user: current_user)
into the /lib/competitions/setup.rb file at line 66. 

We might be able to remove lines 67-69 of the setup file.

Also remove lines 25 and following from the /lib/competitions/data/grants.yml file.

**Comment by jseraf** [comment]
duplicated of #94
