### ISSUE TITLE
Move UsersHelper methods to the user model

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#159]
After a conversation with Jalpa, Mike, and Samir, the appropriate place for these methods is as instance methods in the model because the methods need to be called in controllers for the error messages and the specs.

**Comment by jseraf** [comment]
Helpers are already used in controllers. See:
https://github.com/NUARIG/competitions/blob/develop/app/controllers/grant_reviewers_controller.rb#L26

For specs, see how Devise helpers are included:
https://github.com/NUARIG/competitions/blob/develop/spec/rails_helper.rb#L85

**Comment by mattbaumann1** [comment]
I am currently using the helpers and they are working. However, it was encouraged to make these instance methods and not helpers.

**Comment by jseraf** [comment]
Changes in calling helper methods in the controller were specifically baked into Rails 5: https://github.com/rails/rails/pull/24866

Unless there is business logic reasoning to put a method in the model, I'd advocate to keep it as a  helper.

**Comment by jseraf** [comment]
See comment above re helpers in controllers in Rails 5
