### ISSUE TITLE
set up deployment schedule to FSM server

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#166]
deploy early and often so users can test everything. a sandbox, if you will

Laura will talk to Jalpa about deployment and testing

**Comment by lmkw** [comment]
1. Plan to deploy at the end of every sprint if the changes are completed
2. Leave generally one week for testing (UI front end, rake tasks, cron jobs)
3.  Build a ticket for deployment into next sprint 
4. If everything is okay after one week, deploy to production; Summarize issues that required software changes in a description of the version being released; Use labels for versions

**Comment by firaswehbe** [comment]
1. Merge a sprint's work onto `develop` (staging) at the end of every sprint if the changes are completed
2. Leave generally one week for testing (UI front end, rake tasks, cron jobs) on `develop` 
3. Build tickets for deployment/feedback/testing into next sprint (ticket for staging deployment, testing, production deployment) if needed, also notify relevant people such as users who opened tickets
4. If everything is okay after one week, merge `develop` into `master`deploy`; Summarize issues that required software changes in a description of the version being released; Use labels for versions
5. If ticket was done but you find a problem, mark it as being worked on in another sprint/project
6. Deployment and testing is part of the sprint workload, not outside it
7. Name branches for their sprint
