### ISSUE TITLE
SMTP settings for CD2H servers

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#169]
Similar/related to #147.

**Comment by mattbaumann1** [comment]
Dave Eichman emailed 9/4.

**Comment by mattbaumann1** [comment]
@lmkw, can you set up a meeting on Wednesday with Amit and Usman to discuss the SMTP relay and the security scan?

**Comment by mattbaumann1** [comment]
Email sent to David Christensen about possibility of using a northwestern relay for the cd2h.org instance. 9/10.

**Comment by mattbaumann1** [comment]
Dong Fu's response was that we should be using an NIH relay.

**Comment by mattbaumann1** [comment]
David Christensen responded and said that we cannot use the northwestern smtprelay with a non-Northwestern platform. We will need to have Amit and Usman set up a relay.

**Comment by firaswehbe** [comment]
I'm closing this ticket, and marking as resolved. We can open a future ticket if and when the decision comes that we need to use a non-NU email.
