### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#194]
Include NU info and Grant #.

**Comment by firaswehbe** [comment]
Thanks for opening this ticket, @jseraf. Here's the text. Try to make it a medium shade of grey. Logos forthcoming

_Competitions is powered by the Northwestern University Clinical and Translational Sciences Institute (NUCATS) and is supported in part by the National Institutes of Health (NCATS UL1TR001422 and U24TR002306)_

**Comment by firaswehbe** [comment]
*NUCATS* should be hyperlink to https://www.nucats.northwestern.edu

**Comment by firaswehbe** [comment]
I just posted the CD2H logo to teams. Please make it linkable to https://ctsa.ncats.nih.gov/cd2h/

**Comment by firaswehbe** [comment]
I just posted a couple of sanctioned NM FSM logos. Please make it linkable to https://www.feinberg.northwestern.edu/

**Comment by firaswehbe** [comment]
I also posted the NUCATS logo to teams (you can find it under ARIG>CD2H>Files). Please make it linkable to https://www.nucats.northwestern.edu

**Comment by jseraf** [comment]
There's a branch to add this that will be committed pending some branch management (alpha, dev, master).
