### ISSUE TITLE
update rubyzip gem

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#221]
Known high severity security vulnerability detected in rubyzip < 1.3.0 defined in Gemfile.lock.Gemfile.lock update suggested: rubyzip ~> 1.3.0. | Known high severity security vulnerability detected in rubyzip < 1.3.0 defined in Gemfile.lock. | Gemfile.lock update suggested: rubyzip ~> 1.3.0.
Known high severity security vulnerability detected in rubyzip < 1.3.0 defined in Gemfile.lock.
Gemfile.lock update suggested: rubyzip ~> 1.3.0.

**Comment by firaswehbe** [comment]
Thanks @mattbaumann1 -- Is this something needs to go in this project (sprint) ?

**Comment by mattbaumann1** [comment]
I am not sure. This is one of the announcements that came through GitHub.

**Comment by jseraf** [comment]
closed in #224
