### ISSUE TITLE
Upgrade Devise

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#238]
This automated pull request fixes a security vulnerability (High severity).

Learn more about automated security fixes.

Bumps devise from 4.4.3 to 4.7.1.

Changelog
Commits

Dependabot compatibility score

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting @dependabot rebase.

Dependabot commands and options
You can view, comment on, or merge this pull request online at:

  https://github.com/NUBIC/nitro-competitions/pull/20

Commit Summary

Bump devise from 4.4.3 to 4.7.1
File Changes

M Gemfile.lock (48)
Patch Links:

https://github.com/NUBIC/nitro-competitions/pull/20.patch
https://github.com/NUBIC/nitro-competitions/pull/20.diff
—

**Comment by jseraf** [comment]
This was closed in #216
