### ISSUE TITLE
Tracking of winners/awards

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#263]
Publishing results of grants (who won)
Award notifications to winners and applicants

4 votes

**Comment by lmkw** [comment]
Spoke with Dan from EDW and Renee from the Cancer Center and they have a need to notify candidates who have been awarded (as well as keep track of that within Competitions). Some things they mentioned:

-A templated message that they can customize to let applicants know they've been awarded the grant
-A templated message that they can customize to let applicants know they have NOT been awarded the grant

**Comment by mattbaumann1** [comment]
Tracking and notification are two different features, but the design of each should consider the other.
