### ISSUE TITLE
FormBuiler related error on Submission validation error

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#277]
NoMethodError at /grants/<NAME>/submissions
undefined method `remove_document' for #<GrantSubmission::Response:XXXXXXXXXX>

This was found while submitting a submission. To duplicate, have a grant with a document upload and a integer question. Then apply but put text in the int field after uploading a document. 

- [x] GrantSubmission::Question factory to include file_upload trait
- [x] Update GrantSubmission::Question model specs to include file_upload
- [x] GrantSubmission::Response factory for valid and invalid file_upload types
- [x] GrantSubmission::Response model specs for file_upload
- [x] Add spec for successful submission with file_upload question and response 
- [x] Add spec for failed submission with file_upload question and response 
- [x] Add spec for failed submission with valid file_upload response and an invalid response to another field

**Comment by jseraf** [comment]
Error caused by previously removed remove_document methods

**Comment by jseraf** [comment]
Closed in #287
