### ISSUE TITLE
Identify specs for NU Shibboleth SSO

### ISSUE THREAD

**Issue by firaswehbe** [NUARIG/competitions#298]
Main question, would the code work as is to support NU Shibboleth? Opening ticket as placeholder for spec gathering

**Comment by mattbaumann1** [comment]
I believe that the configurations in the /config/initializers/devise.rb file will need to be changed. Right now these are being pulled from the credentials file. It seems like moving forward in the future. It would be good to remove these from the credentials file and place each on their respective servers. 

There will need to be work done with NUIT to make sure that they are receiving the information that they need to process sign-in and sign-out. Depending on what these might be, there may be other variables that will need to be added into the configuration file, if they are different from those used by UNA.

**Comment by jseraf** [comment]
related to #438 
related to #437 

@mattbaumann1 please close if you are handling in other tickets, otherwise reference here as needed.

**Comment by mattbaumann1** [comment]
Closing this ticket.
