### ISSUE TITLE
Guide the user at form creation that the scores are likert-like

### ISSUE THREAD

**Issue by firaswehbe** [NUARIG/competitions#310]

**Comment by lmkw** [comment]
See attached. When creating a grant, you don't have any idea what the scoring scale will look like when one is reviewing a grant. We should show users the scoring scale (the Exceptional 1 2 3 4 5 6 7 8 9 Poor) so that they know what it looks like. It should also say:

_This is the scoring scale that will be shown to reviewers:_

**Comment by lmkw** [comment]
[review criteria show range.pdf](https://github.com/NUARIG/competitions/files/4172681/review.criteria.show.range.pdf)

**Comment by jseraf** [comment]
@lmkw two questions:

- This will add a lot of repetition. Can this just go at the top of the page rather than included on every criteria? 
- Do you envision this to function the same as scoring (i.e. hovering changing color, click scoring)?

**Comment by lmkw** [comment]
- yes, it could be just at the top, with proper text to indicate that it applies to every question. Something like "Each question will be scored according to this scale

- no it should be view-only, we're just demonstrating what it looks like

**Comment by jseraf** [comment]
Updating text to read as follows:

In addtion to "overall impact", you can define the review criteria by which submissions to this grant will be scored.

Scoring matches the [NIH's 9-point range] (link: https://grants.nih.gov/grants/policy/review/rev_prep/scoring.htm) as shown below.

**Comment by jseraf** [comment]
@lmkw Does this look right? 

<img width="1219" alt="Screen Shot 2020-02-13 at 2 08 07 PM" src="https://user-images.githubusercontent.com/12803547/74475657-6f10df80-4e6d-11ea-8e13-bb4c0e08956a.png">

**Comment by lmkw** [comment]
@jseraf yes, looks good. If I'm being picky, while you're here I would align the checkboxes with the left edge of either "Criterion Name" and "Instructions / Help Text" OR with the boxes provided for both of those. So like

[ ] Required
[ ] Show comment field

but this ticket is not for that, so I'll leave to your discretion.

**Comment by jseraf** [comment]
@lmkw Went with the latter:
<img width="1332" alt="Screen Shot 2020-02-13 at 3 07 56 PM" src="https://user-images.githubusercontent.com/12803547/74478265-a766ec80-4e72-11ea-8f18-6738a08b87e9.png">

**Comment by lmkw** [comment]
lovely
