### ISSUE TITLE
lay out plan for moving off of NITRO Competitions

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#328]

**Comment by lmkw** [comment]
- [ ] Decide criteria of maturity:
1. simplified sign-in
2. multi-select 
3. ?

- [ ] Make a decision about hosting—use AWS, who will pay? 

- [ ] Figure out date based on that

- [ ] Communication to NITRO community

- [ ] Remove ability to add new competitions or copy existing ones

**Comment by firaswehbe** [comment]
Product of this ticket is detailed inventory of specifications that need to be in place

**Comment by jseraf** [comment]
This is a NITRO issue and can be addressed in that repo
