### ISSUE TITLE
Design: Document and/or improve UI for grant admin actions

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#332]
Some show/hide logic may not make sense to users.  Since these permissions were built out piecemeal over time, it would be good to think through them more systematically. 

The goal should be to create additional:
- banners, help text, tool tips, etc.
- github.io documentation

Related to #379

**Comment by jseraf** [comment]
Related to #379

**Comment by lmkw** [comment]
Based on building a grant with Ellen from UMass, I opened #412, #413, #415 and #416

**Comment by mattbaumann1** [comment]
Closed since most is done. The last pieces are in #942 and #413.
