### ISSUE TITLE
organization_admin to system_admin migration failing on db:migrate

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#335]
20190725192124_change_user_organization_role_to_system_admin.rb fails when called from rake db:migrate but works when loading from schema

`PG::SyntaxError: ERROR:  syntax error at or near "USING"
LINE 1: SELECT 'boolean USING (CASE system_admin WHEN ''admin'' THEN...
               ^
CONTEXT:  invalid type name "boolean USING (CASE system_admin WHEN 'admin' THEN 't'::boolean ELSE 'f'::boolean END)"
: SELECT 'boolean USING (CASE system_admin WHEN ''admin'' THEN ''t''::boolean ELSE ''f''::boolean END)'::regtype::oid`

**Comment by mattbaumann1** [comment]
I think this was fixed in #566. This ticket will be closed.
