### ISSUE TITLE
Allow multiple proposal editors

### ISSUE THREAD

**Issue by mellybelly** [NUARIG/competitions#340]
Users should be able to collaborate on a proposal prior to its submission. Perhaps this is enabled already but I am uncertain how to make it so. Obviously one would not expect concurrent editing, so a lock on the file notification would be warranted in such cases when a permitted user logs into a given proposal record.

**Comment by jseraf** [comment]
@mellybelly this does not currently exist.

Related to #248

**Comment by jseraf** [comment]
This issue has been addressed in #856. Additional work can be done in subtickets.
