### ISSUE TITLE
data export for CD2H phase III submissions

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#345]

**Comment by lmkw** [comment]
[1:52 PM] Laura Wimbiscus
    Hi Devs !  We need to export all the submissions to a Competitions grant in a somewhat user-friendly format. (They want to open the submissions up to public comments, and will posting the submissions on Google Docs)  We have not built any functionality, like, say, Export, to make this possible, so it would have to be a back end job. Any suggestions for Matthew John Baumann on how to do this with the least amount of effort and pain possible?

​[1:59 PM] Jalpa Rameshbhai Patel
    Simplest could be nightly rake task, which export all the data into csv format, which can be be imported in google docs later.
(1 liked)​[2:00 PM] Jalpa Rameshbhai Patel
    
something like below

 desc 'studies data export'
 task export_study_data::environmentdo
csv_file = "#{Rails.root}/tmp/study_data.csv"
csv_header = ['study_identifier', 'irb_number', 'pi_name', 'name', 'status']
CSV.open(csv_file, 'w', write_headers:true) do |csv|
csv << csv_header
Study.includes(:principal_investigator).approved.find_each do |study|
csv << [study.study_identifier, study.irb_number, study.principal_investigator_name, study.name, study.irb_status]
end
end
end

​[3:20 PM] Jalpa Rameshbhai Patel
    or automatic upload to google sheet can be done via API, https://developers.google.com/drive/api/v3/quickstart/ruby



**Please include all the following questions, in this order**

1. Project Title
2. What is the short title of the project?
3. Please list the project lead(s); or whom we should contact with questions regarding the proposal [do you want to omit email addresses?]
4. List the Core(s) with which this project is aligned:
5. With which CTSA program priorities does this proposal align?
6. Outline how successful completion of the project will benefit individual hubs, the overall CTSA Program, or both
7. How will this project engage the CTSA community and beyond? List all proposed members and hubs and/or plan to solicit members.  Outline a clear engagement plan, including: communication channels, outreach efforts, collaboration opportunities.
8. How do you plan to assess the project's success?  How will you identify and mitigate risks and shortcomings? 
9. What is the probability of adoption or implementation of the projects' deliverable within the CTSA community upon project completion? What will help or hinder adoption/implementation?
10. What central resources does this project rely on if any? Please include institutional, CD2H, or NCATS resources.
11. Please upload a Project Plan [500 word limit, excluding references and figure legends].  Please include a project timeline with deliverables [in table format].
12. If this is a continuation of a earlier CD2H project, please describe progress during the prior period.

**Comment by jseraf** [comment]
Request completed via rake task installed on server.

Related to #256 and #268
