### ISSUE TITLE
Not null violation for banner spec failing.

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#346]
Failing spec: not null violation for banner.

rspec ./spec/system/banners/banners_spec.rb:178

Failures:

  1) Banners PaperTrail tracks whodunnit
     Failure/Error: @banner = create(:banner)
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "banner_id" violates not-null constraint
       DETAIL:  Failing row contains (3, Banner, 565, null, create, null, null, 2020-01-22 09:37:21.99602).
       : INSERT INTO "banner_versions" ("item_type", "item_id", "event", "created_at") VALUES ($1, $2, $3, $4) RETURNING "id"
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_banners_paper_trail_tracks_whodunnit_597.png

     
     # /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/paper_trail-10.1.0/lib/paper_trail/record_trail.rb:77:in `record_create'
     # /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/paper_trail-10.1.0/lib/paper_trail/model_config.rb:41:in `block in on_create'
     # /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/factory_bot-4.11.1/lib/factory_bot/configuration.rb:18:in `block in initialize'
     # /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/factory_bot-4.11.1/lib/factory_bot/evaluation.rb:18:in `create'
     # /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/factory_bot-4.11.1/lib/factory_bot/strategy/create.rb:12:in `block in result'
     # /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/factory_bot-4.11.1/lib/factory_bot/strategy/create.rb:9:in `tap'
     # /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/factory_bot-4.11.1/lib/factory_bot/strategy/create.rb:9:in `result'
     # /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/factory_bot-4.11.1/lib/factory_bot/factory.rb:43:in `run'
     # /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/factory_bot-4.11.1/lib/factory_bot/factory_runner.rb:29:in `block in run'
     # /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/factory_bot-4.11.1/lib/factory_bot/factory_runner.rb:28:in `run'
     # /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/factory_bot-4.11.1/lib/factory_bot/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./spec/system/banners/banners_spec.rb:172:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "banner_id" violates not-null constraint
     #   DETAIL:  Failing row contains (3, Banner, 565, null, create, null, null, 2020-01-22 09:37:21.99602).
     #   /Users/mjb0760/.rvm/gems/ruby-2.6.5/gems/paper_trail-10.1.0/lib/paper_trail/record_trail.rb:77:in `record_create'

Finished in 1.7 seconds (files took 2.02 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/system/banners/banners_spec.rb:178 # Banners PaperTrail tracks whodunnit

**Comment by jseraf** [comment]
@mattbaumann1 cannot recreate. Can you confirm this is still an issue?

**Comment by jseraf** [comment]
spec passes.
