### ISSUE TITLE
Long text error reporting is not helpful

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#350]
When a long text answer is too long (more than 4000 char) it provides the following error. 

"Response {:one=>"is too long (maximum is 1 character)", :other=>"is too long (maximum is %{count} characters)"}"

This should be adjusted to be more helpful.

In addition, it should be considered whether this should have a greater limit than 4000 char.

**Comment by firaswehbe** [comment]
We won't fix this one because we're working on doing away with the 4000 character limit in #353
