### ISSUE TITLE
Progress bar on file upload

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#352]
File upload confirmations. Contact a user who had this issue.

Look in to jQuery or Foundation file upload progress bar.

**Comment by jseraf** [comment]
If I understand the issue, I don't think we can address this. We aren't dynamically saving drafts in progress (a la gmail). The submission form needs to be submitted, file validations passed for the file to be saved on upload. 

@lmkw Can we confirm the details of this issue and reassign back to me with more specifics? Seems that Connor's email on 1/16 "[allhands] Competitions platform - file upload confirmation" was the source of the ticket.

**Comment by lmkw** [comment]
This was Connor's exact email:
Hi Laura,
 
An additional Competitions tool/feature request: confirmation/notification when the file upload has been successful.  Currently the system doesn’t acknowledge this, and some submitters have reached out to make sure/ask if their files came through.
 
Thanks!
Connor

**Comment by lmkw** [comment]
From Connor:

Hi Laura,
 
Either a pop up confirmation or something more obvious that the upload was successful would be nice.  I’ve realized the size of the text boxes are changeable – ie you can drag the box to make it larger; but I’m not sure that is obvious to everyone.  This impacts if the uploaded file is viewable in the submitter’s screen.
 
Along these lines, an email confirmation of a successful submission of the grant application/proposal would also be great.
 
Thanks!

**Comment by jseraf** [comment]
![Screen Shot 2020-02-17 at 11 23 36 AM](https://user-images.githubusercontent.com/12803547/74674938-0af56080-5178-11ea-9dba-bae5e60a5760.png)

For questions with long text, the cell containing the file upload input does not expand on upload to accommodate the file name's text.

**Comment by jseraf** [comment]
Temporarily addressed in #380 by setting a minimum cell width. 

Related to #81.
