### ISSUE TITLE
Desired behavior: Admins can re-open submission by switching to Draft 

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#371]
Should a submission be locked in its current state once it has been submitted or should it be able to be updated? If it can be updated once submitted, who should be able to make these updates?

system admins?
grant admins?
applicants?

**Comment by firaswehbe** [comment]
Desired behavior: decree on 2020-02-25 meeting. The admins (system + grant) can switch the status from submitted back to draft. The original submitted then goes in and makes edits then submits.

**Comment by jseraf** [comment]
Per conversation with @lmkw, Submissions that have completed reviews may not be edited.
