### ISSUE TITLE
Use autocomplete instead of dropdown for new grant permission

### ISSUE THREAD

**Issue by firaswehbe** [NUARIG/competitions#372]
In the following route:
`/grants/{grantname}/grant_permissions/new`

The list of users in the drop down would get pretty long as the number of users grows. Consider using autocomplete test box.

**Comment by mattbaumann1** [comment]
explore select2

**Comment by mattbaumann1** [comment]
@lmkw I wanted to check and see what the best text is for the following in the space of "Find an email address" 
<img width="1153" alt="Screen Shot 2020-11-19 at 11 45 58 AM" src="https://user-images.githubusercontent.com/10729154/99705319-31299300-2a5f-11eb-9bdb-7066651dc9a5.png">

**Comment by lmkw** [comment]
Either:

Search

or

Type to find an email address

Search is more succinct. Type tells exactly what you need to do to find results (in lieu of just clicking on the arrow)
