### ISSUE TITLE
Add guidance to Grant admin pages

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#379]
Inspired by #310, review the other Admin tabs for guidance on what the Page does. 

e.g. The Permissions page should describe the differences between user types. The Submission Form page should explain how questions / sections work.

**Comment by lmkw** [comment]
![Review Criteria page](https://user-images.githubusercontent.com/12861678/76886238-781b1500-684e-11ea-8da7-29e2b1a34c67.png)

**Comment by lmkw** [comment]
![Permissions page](https://user-images.githubusercontent.com/12861678/76899580-d7385400-6865-11ea-9024-d7a1a7eac7e3.png)

**Comment by jseraf** [comment]
Changed intro text to: "Reviewers will use this criteria to assess their assigned submissions. You may also provide instructions and guidelines to help them score the submissions."

**Comment by jseraf** [comment]
Multiple PRs closed.
