### ISSUE TITLE
Meeting for requirements gathering for panels

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#393]
Talk to Lauren Daniels, Abby Cosentino-Boehm and possibly Phil Hochberger about the panel review process

**Comment by firaswehbe** [comment]
Meeting participants:

* [ ] Lauren
* [ ] Adam
* [ ] Abby
* [ ] Phil Hockberger

**Comment by lmkw** [comment]
Pasting notes from speaking with Lauren:
**LOIs**
Does LOIs through REDCap
LOI is not required but may help to weed out non-qualified candidates 
LOIs used to be one page email sent to NUCATS email; but there’s a lot of info Lauren needs to know to figure out potential conflicts of interest, who can be a reviewer, also need demographic data for reporting purposes, need to be US citizen because federal award
also need department, primary mentor, dept chair and division chief
Helps us start to figure out where department may not have enough internal reviewers
This is why she puts it in a REDCap form, reporting out is so much easier, e.g.
She also keeps REDCap form open in case changes need to be made (for example, mentor changes)
It is cumbersome to use two systems

**Panel**
Physical meeting but many people join by phone
Do want to control what people see, e.g. Would like to hide budget from reviewers because this is not a criteria for review, just a thing NU does to get the applicant thinking about it; They’ll get help with the final budget if they’re chosen for the award

Ways to see de-identified grant reviews! is a nice-to-have

Biggest issue with panel review using current NITRO Competitions layout, different ways to access proposal vs proposal with files, depending on monitor using, didn’t realize they needed to scroll horizontally, would miss files, etc
The title of the application hyperlinked, would click on that to get to the files 

For reviews, wants to see best scores on top (impact not composite)
It would be good for reviewers to see applicant, overall impact score and an ability to go into the full review tab
Usually second round of scoring during the meeting, they make cut-off of certain score, say 3.0, and only review submissions above that score, people step out of the room if they have a conflict of interest, pass out slip of paper, write their score; those who actually reviewed grant get to say their range, oftentimes stick with preliminary score, those on the phone have to email their score after each discussion
3 staff members who staff, collect, input in Excel, re-rank in real time, before reviewers leave room agree upon who finalists will be, but there’s some wiggle room. finalist interviews after that, more so a way to gauge primary mentor support

It would be amazing if there was an export option like there is in REDCap, for NIH reporting and to have one hard copy of everything in the room

**Comment by lmkw** [comment]
Emily and Adam agreed that Lauren had covered everything, they just wanted to add this:

"I touched base with Lauren and I believe she captured everything. The ability to export application fields into an excel spreadsheet would make some of our tracking and evaluation efforts quite a bit easier but other than that, I think Lauren will have more information for you after the KL2 review. The KL2 review is more particular and rigid than the TL1, so we can adapt the TL1 to the KL2 framework easier than the other way around. "
