### ISSUE TITLE
re-submitting does not change timestamp of submission

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#398]
John submitted a...submission at 10AM
Then he asked me, the admin, to revert it to draft so he could change something
I did
John resubmitted at 3PM
Result: In the table of submissions, the timestamp for when his submission was...submitted is still 10AM. 
It should reflect the updated submission time
This is just so the submitter and the admin are clear that John's update happened without having to open up the application and check for changes

**Comment by jseraf** [comment]
Should "Submitted at" say "Last Updated" (or something similar).

**Comment by lmkw** [comment]
yes, that's a good idea

**Comment by mattbaumann1** [comment]
The label for this is "Submitted On" but it populates with the created_at date time. Would it be better to change the label or change the value?
