### ISSUE TITLE
State Transition Abstractions

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#403]
Add [aasm](https://github.com/aasm/aasm) to manage state transitions and associated validations.

Initial use case is managing Submission draft/submitted validations. Will also be used in Grant and Review.

**Comment by jseraf** [comment]
AASM doesn't seem to have good support for validating associations conditionally. Scheduling some time w/ Yulia to discuss how StudyBudget handles similar issues.

**Comment by firaswehbe** [comment]
Proposed definition of done "Decision on which gem to use to manage state transitions in general for Submission, Reviews, Grants"

**Comment by jseraf** [comment]
AASM doesn't play well with nested attributes. Submission transitions are coded in the Submission and Review model
