### ISSUE TITLE
Throws error when section without title is created

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#408]
It allows you to create a section without a title and save it. It only becomes a problem when the grant is published.

to recreate:
edit submission form
add section (without title)
add a question to the section(fill out completely)
save the submission form
publish the grant

The following error appears.
No route matches [GET] "/grants/dtg/forms/31"
Rails.root: XXXXXXXXX
Application Trace | Framework Trace | Full Trace
Routes
Routes match in priority from top to bottom

**Comment by jseraf** [comment]
This occurs when Publishing from an admin that failed an error. 

Simplest fix would be to change from  redirect_back to send all publish requests to the grant edit page.
