### ISSUE TITLE
Add "All Reviews" summary page per Submission

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#420]
New admin page that is similar to the "All Reviews" page in NITRO Competitions, but limited to just one submission.

Page should include:
- Header includes Applicant name, Project Title, Grant Name (look for whether a partial can be shared w/ other views)
- Criteria section with each Criteria along with comment and score from each Reviewer (identified? de-identified?)
- Overall Impact section with each Reviewer's comment and score.  
- Submission Scores section with Composite Score (i.e. avg of all scored Criteria) and Overall Impact Average (i.e. avg of all Overall Impact scores)

**Comment by jseraf** [comment]
@lmkw What do you think of this? Should anything be more prominent, spaced differently, highlighted, etc?
<img width="940" alt="Screen Shot 2020-03-23 at 12 06 21 PM" src="https://user-images.githubusercontent.com/12803547/77342956-f4a26d80-6cfe-11ea-9552-5b23b5fe8b87.png">

**Comment by lmkw** [comment]
Talked through with John 3/34/2020
Possible future features: 

- anchor link individual scores (e.g. Reviewer Sterling Morrison's Significance score) to the comments for that score below

- when scores can be cached, make each column sortable so admin can easily see highest scores in any given category

- add an average score for each column
