### ISSUE TITLE
Create plan for AWS certificate changes on all servers

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#424]
On 3/18/20, 6:06 AM, "Amazon Web Services, Inc." <no-reply-aws@amazon.com> wrote:

    Hello,

    In 2018, AWS announced a broad migration of AWS services’ SSL/TLS certificates to our own Certificate Authority, Amazon Trust Services. Consistent with this change, and beginning March 2021, Amazon S3 and Amazon CloudFront will begin migrating the Certificate Authority for each services’ default certificate. Using our own Certificate Authority, AWS services can better manage the security practices used to handle our default certificates.

    Your action may be required to ensure your applications continue normal operation after this change. If you already use other AWS services, your application most likely already trusts Amazon Trust Services as many AWS services have already migrated. Visit https://urldefense.com/v3/__https://www.amazontrust.com/repository/__;!!Dq0X2DkFhyF93HkjWTBQKhk!DbDkGiD0RhcX2kM7lAnJh04D3NjS_UkvcclrxEgiiQsFqxpdjA7xQ3NexpWq-fk9P-3ScjWmaXxq$  for more information about Amazon Trust Services.

    To prepare for this migration, visit the announcement blog or review the FAQs below:
    https://urldefense.com/v3/__https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/__;!!Dq0X2DkFhyF93HkjWTBQKhk!DbDkGiD0RhcX2kM7lAnJh04D3NjS_UkvcclrxEgiiQsFqxpdjA7xQ3NexpWq-fk9P-3Scv5LaJtJ$

    If you have additional questions, or require additional assistance, please open a case in the AWS Support Center: https://urldefense.com/v3/__https://aws.amazon.com/support__;!!Dq0X2DkFhyF93HkjWTBQKhk!DbDkGiD0RhcX2kM7lAnJh04D3NjS_UkvcclrxEgiiQsFqxpdjA7xQ3NexpWq-fk9P-3Sckc2z1bN$

    Please also monitor each services’ AWS Forums page for future updates as the migration date approaches:
    Amazon S3 Forum https://urldefense.com/v3/__https://forums.aws.amazon.com/forum.jspa?forumID=24__;!!Dq0X2DkFhyF93HkjWTBQKhk!DbDkGiD0RhcX2kM7lAnJh04D3NjS_UkvcclrxEgiiQsFqxpdjA7xQ3NexpWq-fk9P-3ScrdOtNC8$
    Amazon CloudFront Forum https://urldefense.com/v3/__https://forums.aws.amazon.com/forum.jspa?forumID=46__;!!Dq0X2DkFhyF93HkjWTBQKhk!DbDkGiD0RhcX2kM7lAnJh04D3NjS_UkvcclrxEgiiQsFqxpdjA7xQ3NexpWq-fk9P-3ScryTjbNF$

    Frequently Asked Questions
    Q1: What is changing?
    The certificate authority for Amazon S3 and Amazon CloudFront’s default certificates are changing from DigiCert to Amazon Trust Services. For S3, many regions already use Amazon Trust Services including all regional endpoints for the eu-west-3, eu-north-1, me-south-1, ap-northeast-3, ap-east-1, and us-gov-east-1 regions. S3 will be migrating the remaining AWS regions to Amazon Trust Services as well. For CloudFront, all edge locations will be migrating to Amazon Trust Services.

    This does change does not impact workloads that use HTTP only or use a custom SSL/TLS certificate.

    Q2: When are these changes occurring?
    The changes in Certificate Authority will begin rolling out on March 1, 2021.

    Q3: What do I need to do?
    Evaluate whether your applications trust Amazon Trust Services’ root certificates. If your application does not trust Amazon Trust Services, perform one of the following two actions. Resolution option 1, update your client certificate trust store to include all of Amazon Trust Services’ root certificates. Resolution option 2, change the domain name your application requests to a CloudFront Alternative Domain Name (CNAME) that uses an SSL/TLS certificate from an already trusted Certificate Authority.

    Q4: How do I test if my application trust Amazon Trust Services?
    Verify your application works with Amazon Trust Services issued certificates, by performing one of the following tests from within your application. Test option 1, fetch the object https://urldefense.com/v3/__https://s3-ats-migration-test.s3.eu-west-3.amazonaws.com/test.jpg__;!!Dq0X2DkFhyF93HkjWTBQKhk!DbDkGiD0RhcX2kM7lAnJh04D3NjS_UkvcclrxEgiiQsFqxpdjA7xQ3NexpWq-fk9P-3Sco2ewUSn$  and verify a 200 response or that you see the green check mark in the test image. Test option 2, create an S3 bucket in your AWS account in any of the following regions (eu-west-3, eu-north-1, me-south-1, ap-northeast-3, ap-east-1, and us-gov-east-1) and fetch a test object.

    Q5: What root certificates are part of Amazon Trust Services?
    Refer to https://urldefense.com/v3/__https://www.amazontrust.com/repository/__;!!Dq0X2DkFhyF93HkjWTBQKhk!DbDkGiD0RhcX2kM7lAnJh04D3NjS_UkvcclrxEgiiQsFqxpdjA7xQ3NexpWq-fk9P-3ScjWmaXxq$  for the current list.

    Q6: What happens after March 1, 2021 if my clients do not trust Amazon Trust Services’ Certificate Authorities?
    All client requests made to a default Amazon S3 or Amazon CloudFront endpoint will receive a default certificate issued from Amazon Trust Services. If the client trust store does not trust the Certificate Authority, it may close the connection and report the SSL certificate as “untrusted.”

    Sincerely,
    Amazon Web Services

    Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210

**Comment by mattbaumann1** [comment]
@Firas responded in Teams with the following.
Dong handled certs on alpha. I handled certs on staging and prod. Dave Eichmann minted those two.

**Comment by jseraf** [comment]
Related to #546 and 553

**Comment by jseraf** [comment]
Closing. All instances using AWS have been shut down.  

cc @mattbaumann1
