### ISSUE TITLE
rules for grant state changes (draft, publish, etc)

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#43]
E.g.,
Shouldn't see delete button if can't delete
Shouldn't see draft button if you can't make it a draft

Process:
1. Begin creating grant
2. Choose Save as Draft or Save and Publish
3. If draft, stays draft. If it's published also check Publish Date

Can you edit a published grant?
Yes
Can you edit a published grant with submissions?
Yes

5 STATES:
1. Demo--yes, make it like Study Tracker's STUXXXXXXX with limited access
2. Draft--yes
3. Published--yes
Open and Closed are descriptors of the grant, not states
4. Completed--Grant has been awarded, grant creator fills in the amount was awarded and to whom
5. Archived--Old grants that people don't need to see all the time, automatically happens 180 days after panel review date or input award amount

**Comment by jseraf** [comment]
Includes save / update / publish workflow. 

![IMG_9885](https://user-images.githubusercontent.com/12803547/56588483-0d634a00-65a9-11e9-9534-bc15525cd588.jpg)

**Comment by jseraf** [comment]
Partially addressed in #64. Additional logic to come as submissions are built out.
