### ISSUE TITLE
create example files in /config for all hidden configuration files

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#434]
Create example files for the following.

/config/attribute-map.yml
/config/deploy.config.yml

**Comment by jseraf** [comment]
- [ ] Updating competitions_config.example.yml
  - [ ] Remove storage info
  - [ ] Remove DB info
  - [ ] Add instance-specific things
    - [ ] Email
    - [ ] Name of Application (i.e. header title)
  - [ ] Keep SAML configs
  - [ ] Keep mailer configs
  - [ ] Include comments re: passwords
- [ ] Clean up existing initializers
  - [ ] Remove other environment initalizers from repo
  - [ ] Add an example storage initialzer
  - [ ] Remove current storage initialzer
  - [ ] Add an example environment initializer
- [ ] Switch credentials to secrets
  - [ ] Create secrets file
  - [ ] Move things out of credentials into secrets
  - [ ] Update calls to existing credentials to point to secrets
  - [ ] Remove credentials from the repo
  - [ ] Add example secrets template
- [ ] Update list of prereqs in readme
  - [ ] Add rvm / ruby version to prerequisites
  - [ ] Add postgres to prerequisites
  - [ ] Add shibboleth to prerequisites
  - [ ] Add mailcatcher to prerequisites

**Comment by jseraf** [comment]
initial work for this ticket is complete per #483 and additional tickets created and referenced in #490 based on discussions among the devs as well as with pod leaders.
