### ISSUE TITLE
Add guidance on Grant Form admin page

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#451]
Related to #379, the Submission Form page should explain how questions / sections work.

**Comment by lmkw** [comment]
<img width="1269" alt="Create Grant help text" src="https://user-images.githubusercontent.com/12861678/79773815-88179000-82f7-11ea-8599-667dcd9b7281.png">

**Comment by jseraf** [comment]
The text under the label will be fixed as part of #458 (cc @mattbaumann1)

Suggest changing the help text to something shorter. Maybe something like:
> Generates a short URL to use when advertising or linking to this grant (3-15 characters).

**Comment by lmkw** [comment]
<img width="1272" alt="Submission Form help text" src="https://user-images.githubusercontent.com/12861678/79783680-a6d15300-8306-11ea-931d-6c9ebb1736cb.png">

**Comment by lmkw** [comment]
I say "gray italic text" for the guidance under the Questions header, but it should actually be consistent with the instructional text on the Review Criteria tab, which is not gray, but is italicized. So either both should be gray or both should be black, just want consistency. For what it's worth, it looks like gray italicized smaller text is reserved for help text beneath fields as opposed to instructional text.

**Comment by jseraf** [comment]
Intro test was not added. 

Changing suggested text as follows to match voice on Review Criteria page:
> Applicants will use the questions defined on this page to apply to your grant.

**Comment by lmkw** [comment]
can we change the URL that appears on the Overview page? 
instead of:
http://example.org/ 

change to:
https://competitions.cd2h.org/

**Comment by jseraf** [comment]
@lmkw See [comment above](https://github.com/NUARIG/competitions/issues/451#issuecomment-616716747). This will be fixed after #458.
