### ISSUE TITLE
Guidance on Grant Reviewers admin page

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#452]
Related to #379 - Review/update/add to guidance on Reviewers page

**Comment by lmkw** [comment]
![reviewers](https://user-images.githubusercontent.com/12861678/83828625-be8e4c00-a6a6-11ea-87e1-91c5833a06d4.png)

**Comment by lmkw** [comment]
This switches the placement of the two columns, but not the behavior. I also reduced the text
