### ISSUE TITLE
Guidance on Grant Duplicate landing page

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#453]
Related to #379 - Review/add/update guidance on landing page for Grant duplicate

**Comment by lmkw** [comment]
<img width="1294" alt="Duplicate grant instructional text" src="https://user-images.githubusercontent.com/12861678/79911178-8d530880-83e5-11ea-90b8-8cbc17dbff69.png">

**Comment by lmkw** [comment]
There's a typo on this page, and can we change the text from this:

**Once you update and save, all roles, questions, and criteria will be copied from from [grant name]**

to

**Once you update and save, all questions, criteria, and roles will be copied from [grant name]**
