### ISSUE TITLE
adding configuration documentation to README

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#455]
create a README for first time set up of Competitions, points to example files

Assumptions:
1. They will have RoR installed, x version

**Comment by jseraf** [comment]
- [ ] Add rvm / ruby version to prerequisites
  - [ ] Add postgres to prerequisites
  - [ ] Add shibboleth to prerequisites
  - [ ] Add mailcatcher to prerequisites

**Comment by mattbaumann1** [comment]
@fanglinnw is reviewing the documentation by testing the setup.
