### ISSUE TITLE
Ability to export from Reviews tab

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#459]
On the Reviews tab there should be a button to download an .xls file with the following:

1. Applicant name
2. Submission title
3. Each reviewer's name
4. Each reviewer's overall impact score
5. The applicant's average overall impact score

**Comment by lmkw** [comment]
The download doesn't default to exactly how the reviews are sorted on the page, which is kinda what I would expect, but I don't think this is a showstopper. I imagine users will manipulate the download to their liking. If I'm wrong, we should just wait until someone requests this (provided it's even possible)

**Comment by lmkw** [comment]
getting an error message trying to export this particular set of reviews. others have been fine: https://competitions-staging.cd2h.org/grants/submissionTest2/reviews.xlsx

**Comment by jseraf** [comment]
Excel reserved characters for sheet names: \/*[]:?
