### ISSUE TITLE
Ability to export a .pdf or .docx from the Submissions tab

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#460]
On the Submissions tab there's a table with all submissions, their scores and links to their reviews. If you click on the link to Reviews, the ensuing page collates all the reviews including the criteria and comments from each reviewer. Back on the Submissions tab we should have a way to export/print that ensuing page. It should be a column in the table so that it's easy for the admin to print out all reviews for all the top candidates at once

<img width="1127" alt="Screen Shot 2020-04-13 at 5 58 57 PM" src="https://user-images.githubusercontent.com/12861678/79169286-a5a5a080-7db1-11ea-90bb-e7762fbca4c6.png">

**Comment by lmkw** [comment]
<img width="1149" alt="Screen Shot 2020-04-13 at 6 08 38 PM" src="https://user-images.githubusercontent.com/12861678/79169346-d2f24e80-7db1-11ea-9ec1-f61aa4fc711e.png">

**Comment by jseraf** [comment]
@lmkw does the PDF link in this table imply a PDF of the Submission rather than of the Reviews Summary?

**Comment by lmkw** [comment]
i meant it to be a pdf of the reviews summary for that submission, so it should have a column title that indicates that
