### ISSUE TITLE
a way for admins to delete unfinished submissions

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#484]
Abby and Keith requested this in our discussion 04/24/2020
I said I thought they might see less unfinished submissions in the new Competitions due to other UI changes, but it is currently a problem in NITRO competitions, the submissions list is littered with half-finished or barely-started submissions and it makes it hard to determine how many legit ones there are, and to navigate through the total list

**Comment by jseraf** [comment]
I think this has been addressed:
- Draft submissions are can be deleted. 
- Submitted submissions are complete by definition.  
- Submissions tab sorting shows which are submitted vs draft
