### ISSUE TITLE
panel mode requirement notes

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#485]
--Called it a "Review Session" instead of a panel 
--This mode could be set for a halo period a few days before and after the panel convenes (i.e. a range of days)
--In this mode, all reviewers can see all submissions and reviews
--A way to mark submissions as moving to the final round/review session
--A way for every reviewer at the panel to score submissions for the second time (during the review session)

**Comment by mattbaumann1** [comment]
This ticket has been partially addressed. Other tickets that address the issues here are as follows:
#627 
#250
#704
This ticket will be closed.
