### ISSUE TITLE
Older versions of Safari fail to logout using SAML

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#489]
On sign out we receive the following error when using a Safari browser.

BadRequestError
400 Failed to logout. SAML login session not found.

Sign out works in Chrome and Firefox.  This is happening on all our servers so it seems to not be related to recent changes in our code.

**Comment by mattbaumann1** [comment]
Older versions of Safari are truncating the SAML request on logout. For the time being a banner will be added to all three sites.

**Comment by mattbaumann1** [comment]
NUIT said that they were working on a fix for this last week. We are still having the logout issues with older versions of safari.

**Comment by mattbaumann1** [comment]
Email sent to XiaoXia on 20200526

**Comment by jseraf** [comment]
Issue still occurs with Safari version <= 13.1.1. Follow up sent to Xiaoxia 6/30.

**Comment by jseraf** [comment]
Fixed in #616
