### ISSUE TITLE
Update competitions_config.example.yml

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#491]
- [x] Remove storage info
  - [x] Remove DB info
  - [x] Add instance-specific things
    - [x] Email
    - [x] Name of Application (i.e. header title)
  - [x] Keep SAML configs
  - [x] Keep mailer configs
  - [x] Include comments re: passwords
  - [x] Ensure all files that need to be syymlinked are included in deploy.rb and deploy.example.rb

**Comment by mattbaumann1** [comment]
Closed after merge into open-source branch.
