### ISSUE TITLE
Make the 404 page instance specific

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#494]
In public/404.html, the header and footer include hardcoded email address, etc;.

**Comment by mattbaumann1** [comment]
Remove instance specific information.

**Comment by mattbaumann1** [comment]
Here is a guide for adding dynamic error pages. However, these will only work if Rails is running. If rails doesn't run it will stop the error page from loading. Therefore I will continue to strip out our application name and emails from the 404 to make it more generic as this project is open sourced.

http://www.marcelofossrj.com/recipe/2019/04/14/custom-errors.html

**Comment by mattbaumann1** [comment]
The header and footer were removed.
