### ISSUE TITLE
add select2 gem

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#54]
To prevent dropdown menus from becoming too annoying, we should add the select2 gem.

**Comment by mattbaumann1** [comment]
The select2 gem was added. The use of autocomplete typing should be explored.

**Comment by mattbaumann1** [comment]
#80

**Comment by lmkw** [comment]
Laura, look to see where it may be helpful, if at all, to have autocomplete

**Comment by jseraf** [comment]
Will review after launch.

**Comment by mattbaumann1** [comment]
The gem is used with form-builder and has been added, when needed.
