### ISSUE TITLE
Remove ability to create a new grant

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#545]
Allow current grant administrators access to edit their current grants but remove the ability to create a new grant

**Comment by jseraf** [comment]
@lmkw following up on our teams chat. should there be a warning going out to existing users before this happens?

**Comment by jseraf** [comment]
@lmkw should i just go ahead and do this?

**Comment by lmkw** [comment]
yes. i have no internet and my cell service sucks at home so i’m having a hard time working today

sent from a portable device/please excuse brevity

**Comment by mattbaumann1** [comment]
Is there a problem with just unchecking all the grant_creator access for all users?
