### ISSUE TITLE
build registered_users

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#554]
Create migration and models for two user subclasses RegisteredUser and SamlUser. 
By the end of this ticket, we should have models, controllers, and views for the login of a database authenticatable user in Competitions.   

This will include work with the following.
- [x] migrations
- [x] models
- [x] limit domains
- [x] model specs
- [x] session controllers
- [x] routes
- [x] controllers (confirmations, passwords, registrations)
- [x] views
- [x] block institutional email addresses from signing up as registered users
- [ ] testing

This issue is covered by the umbrella ticket #548 .

**Comment by mattbaumann1** [comment]
Jalpa encouraged me to go back to the ticket #552 before working on the specs for this ticket.

**Comment by mattbaumann1** [comment]
The users have been added and tests need to be written.

**Comment by mattbaumann1** [comment]
Specs will be handled in #590 and this ticket will be closed.

**Comment by lmkw** [comment]
Tried to sign up as a registered user using my Northwestern email and it failed, as it should
