### ISSUE TITLE
Coordinate with FSM IT to decommission alpha

### ISSUE THREAD

**Issue by firaswehbe** [NUARIG/competitions#564]

**Comment by lmkw** [comment]
@mattbaumann1 , @jseraf , what date should it die, and do we need any special data archive consideration?

**Comment by jseraf** [comment]
@lmkw We have no preferences as to date. Note: If you want to keep the competition that you've been using in demos, we can copy the database.

**Comment by mattbaumann1** [comment]
I will create a dump of the db.

**Comment by mattbaumann1** [comment]
Email sent with the db dump.

**Comment by lmkw** [comment]
From Eamon, 9/14/2020:
Good morning Laura, 
I have removed all of our management tools and will assign this decommission over to Dong for deletion of the machines. 
Thanks,
Eamon

**Comment by lmkw** [comment]
Done 09/15/2020, AWS account closed as well
