### ISSUE TITLE
Update 'Are you sure?' confirmation messages to be more explicit

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#578]
e.g. "This will delete [do this/that]. Are you sure?"

**Comment by lmkw** [comment]
John will post links to the specific pages, Laura will come up with text

**Comment by lmkw** [comment]
Deleting someone from the Permissions tab:
Are you sure you want to remove [person's name] from this grant?

Deleting a banner:
Are you sure you want to delete this banner entirely? To take it down without deleting it, uncheck the Visible box.

Deleting a grant:
Are you sure you want to delete this grant entirely? 

Deleting parts of the submission form:
Are you sure you want to delete this [question/section]?

**Comment by lmkw** [comment]
_Deleting someone from the Permissions tab: 
Are you sure you want to remove [person's name] from this grant?_
The text reads "Are you sure you want to remove Matthew Baumann name from this grant?"
Can you remove "name" from that?

__Deleting a banner: Are you sure you want to delete this banner entirely? To take it down without deleting it, uncheck the Visible box._ 
This was not implemented; It just says:
<img width="348" alt="Screen Shot 2020-12-14 at 4 04 27 PM" src="https://user-images.githubusercontent.com/12861678/102141292-31cb0480-3e26-11eb-8b53-dc76280643f1.png">


_Deleting a grant:
Are you sure you want to delete this grant entirely?_
This works


_Deleting parts of the submission form:
Are you sure you want to delete this [question/section]?_
This was not implemented. If you try to delete a question, it says:
<img width="298" alt="Screen Shot 2020-12-14 at 4 05 13 PM" src="https://user-images.githubusercontent.com/12861678/102141313-3c859980-3e26-11eb-8c3a-e913577c09ac.png">

**Comment by jseraf** [comment]
@lmkw the submission_form confirm can't be question/section specific due to form_builder complications. To be fixed at a later date.

**Comment by jseraf** [comment]
@lmkw 
- Banner confirm fixed. Was mistakenly implemented on only the edit page.
- Permission typo fixed.
