### ISSUE TITLE
Update outgoing registered user email subject and content

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#582]
Currently uses default Devise templates with no customization.

e.g. [user confirmation email](https://github.com/NUARIG/competitions/blob/develop/app/views/devise/mailer/confirmation_instructions.html.erb) subject is "_Confirmation instructions_" and makes no reference to the application.

**Comment by mattbaumann1** [comment]
I am not sure whether it is a good idea to change the subject lines for the mailers. Here is what would be involved. Not too extensive, but heavier than leaving them with the factory defaults. 

https://solidfoundationwebdev.com/blog/posts/how-to-change-the-subject-of-a-devise-email

**Comment by mattbaumann1** [comment]
@jseraf will look into customizing the subject lines in a separate ticket.
