### ISSUE TITLE
Review/update Help pages

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#608]
Link to [generic help page](https://data2health.github.io/competitions-project/) and [login help page](https://data2health.github.io/competitions-project/howto_login.html) are hardcoded in the repo. These pages are very specific to the CD2H and UNA. 

Should we delete this section? Create a new, generic github page? Include help pages in the repo?

**Comment by jseraf** [comment]
Make the help URL configurable.

**Comment by mattbaumann1** [comment]
Relates to #332
