### ISSUE TITLE
Create Release 1.2 branch

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#645]
Create and deploy release 1.2 branch which merges the Rails 6 upgrade, #279 , to develop and deploy it to staging for testing. 

- [x] merge rails 6 branch into develop
- [x] create release/1.2 branch
- [x] deploy to staging server.

**Comment by mattbaumann1** [comment]
There is an error in deployment with yarn missing on the server. An email has been sent to IT for the installation. 

00:28 bundler:install 
      The Gemfile's dependencies are satisfied, skipping installation 
00:29 deploy:assets:precompile 
      01 /usr/local/rvm/bin/rvm ruby-2.6.6 do bundle exec rake assets:precompile 
      01 Yarn executable was not detected in the system. 
      01 Download Yarn at https://yarnpkg.com/en/docs/install 
      01 rake aborted! 
      01 Sass::SyntaxError: File to import not found or unreadable: settings. 
      01 Load paths:

**Comment by jseraf** [comment]
release branch was created, tested, and merged in #648
