### ISSUE TITLE
Testing of release 1.2

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#646]
Once the release of 1.2 has been deployed to staging, #645, the application should be tested. 
There should be general testing, but these are the most likely places to find new errors, based on changes. 

- [x] updating a submission
- [x] updating a grant
- [x] Test uploads

Currently blocked by #645

**Comment by lmkw** [comment]
There were current uploads that I was not able to see, but I could upload new .pdfs that I was then able to see.
