### ISSUE TITLE
Mailer hit an error on the granting grant creator permission

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#664]
I, [2020-10-29T13:35:14.887069 #446]  INFO -- : [c1e6dd51-e332-411c-8975-82105f4ce3ee]   Rendering grant_creator_request_review_mailer/approved.html.haml within layouts/mailer
I, [2020-10-29T13:35:14.901765 #446]  INFO -- : [c1e6dd51-e332-411c-8975-82105f4ce3ee]   Rendered grant_creator_request_review_mailer/approved.html.haml within layouts/mailer (Duration: 14.6ms | Allocations: 1938)
D, [2020-10-29T13:35:14.911998 #446] DEBUG -- : [c1e6dd51-e332-411c-8975-82105f4ce3ee] GrantCreatorRequestReviewMailer#approved: processed outbound mail in 26.7ms
I, [2020-10-29T13:35:19.968647 #446]  INFO -- : [c1e6dd51-e332-411c-8975-82105f4ce3ee] Delivered mail 5f9b0b62ded9a_1be1652f9c7578f@vfsmcdsiapps03.fsm.northwestern.edu.mail (5056.5ms)
D, [2020-10-29T13:35:19.968734 #446] DEBUG -- : [c1e6dd51-e332-411c-8975-82105f4ce3ee] Date: Thu, 29 Oct 2020 13:35:14 -0500
From: competitions-noreply@northwestern.edu
To: j-xxxxxx@northwestern.edu
Message-ID: <5f9b0b62ded9a_1be1652f9c7578f@vfsmcdsiapps03.fsm.northwestern.edu.mail>
Subject: Competitions: Approved Grant Creator Request
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
<head>
<meta content='text/html; charset=utf-8' http-equiv='Content-Type'>
<style>
  /* Email styles need to be inline */
</style>
</head>
<body style='font-family: helvetica,arial,sans-serif'>
<p>
Dear Xxxxx Xxxxxx,
</p>
<p>
You request for Grant Creator rights in <a href="https://competitions.fsm.northwestern.edu:/">Competitions</a> has been approved.
</p>
<p>
After you log in, you can create a new Grant by visiting:<br/>
<a href="https://competitions.fsm.northwestern.edu:/profile/grants">https://competitions.fsm.northwestern.edu:/profile/grants</a>
</p>
<p>
If you have any questions or would like to request a demo, please reply to this email.
</p>
<p>
Happy grantmaking!
</p>
<p>
Thank you.
</p>

</body>
</html>

I, [2020-10-29T13:35:19.968984 #446]  INFO -- : [c1e6dd51-e332-411c-8975-82105f4ce3ee] Completed 500 Internal Server Error in 5122ms (ActiveRecord: 22.5ms | Allocations: 12267)
F, [2020-10-29T13:35:19.969563 #446] FATAL -- : [c1e6dd51-e332-411c-8975-82105f4ce3ee]   
[c1e6dd51-e332-411c-8975-82105f4ce3ee] Net::SMTPAuthenticationError (535 5.7.3 Authentication unsuccessful
):
[c1e6dd51-e332-411c-8975-82105f4ce3ee]   
[c1e6dd51-e332-411c-8975-82105f4ce3ee] app/controllers/grant_creator_requests/review_controller.rb:33:in `send_notification'
[c1e6dd51-e332-411c-8975-82105f4ce3ee] app/controllers/grant_creator_requests/review_controller.rb:10:in `update'
I, [2020-10-29T13:35:30.248084 #446]  INFO -- : [652fdae0-c091-4b9c-920f-069276b02f84] Started GET "/grant_creator_requests" for 165.124.166.149 at 2020-10-29 13:35:30 -0500
I, [2020-10-29T13:35:30.249036 #446]  INFO -- : [652fdae0-c091-4b9c-920f-069276b02f84] Processing by GrantCreatorRequestsController#index as HTML
D, [2020-10-29T13:35:30.254378 #446] DEBUG -- : [652fdae0-c091-4b9c-920f-069276b02f84]   SamlUser Load (1.9ms)  SELECT "users".* FROM "users" WHERE "users"."type" = $1 AND "users"."id" = $2 ORDER BY "users"."id" ASC LIMIT $3  [["type", "SamlUser"], ["id", 1], ["LIMIT", 1]]
D, [2020-10-29T13:35:30.259256 #446] DEBUG -- : [652fdae0-c091-4b9c-920f-069276b02f84]    (3.0ms)  BEGIN
D, [2020-10-29T13:35:30.262806 #446] DEBUG -- : [652fdae0-c091-4b9c-920f-069276b02f84]   AuditAction Create (3.2ms)  INSERT INTO "audit_actions" ("user_id", "controller", "action", "browser", "params", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["user_id", "1"], ["controller", "grant_creator_requests"], ["action", "/grant_creator_requests"], ["browser", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"], ["params", "{}"], ["created_at", "2020-10-29 13:35:30.255722"], ["updated_at", "2020-10-29 13:35:30.255722"]]

**Comment by jseraf** [comment]
w/ @mattbaumann1 Updated mailer config in competitions config to remove errant `:` in outgoing email. Also email settings in secrets on prod. Tested and confirmed an outgoing grant creator requested.
