### ISSUE TITLE
Create excel export of submissions

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#667]
Create excel export for submissions. This should be one row per submission with column headings being the questions.

**Comment by lmkw** [comment]
Possibly two manifestations: Export of all answers (including filenames instead of files?) and an export of all documents for a submission

**Comment by lmkw** [comment]
Asked 4 different people (Emily, Keith, Eleanor and Adam) and the consensus was this should be called "Export All Submissions"
