### ISSUE TITLE
Test release/1.3 branch on staging

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#674]
Includes:
#661 - feature/panels (and sub issues, e.g. #638, #651, #653, etc)
#656 - standardize grant headers and breadcrumbs
#668 - add review comments to excel export reviews
#659 - add MyPanels page
#654 - pin footer to bottom of browser window 
#676 - Action submenu on grant edit pages
#547 - Standardize search forms
#682 - Layout not working safari
#677 - Make draft/published button less intrusive
#669 - Admins can delete admin submissions in published grant
#683 - Users without grant permissions shouldn't be able to access submissions index

**Comment by lmkw** [comment]
#661 , is it possible to automatically populate the end date of the panel with the date/time chosen for the start date + 1 hour?  When I went to set up mine, I picked the start date and the end date was months prior, so it gave me an error. I expected the error, it would just be nice to pre-empt that. If this is indeed possible, we can put it in a new ticket. 
Also, the widget populates military time. It would be nice if it showed AM/PM instead. Again, okay to put in a new ticket.

#668 looks great. I discovered that I get an error message if I try to export when one of the reviews is incomplete. We should probably examine that

#676 I don't see these?
#669 I don't see this either

**Comment by jseraf** [comment]
@lmkw bug in #668 is fixed and deployed (#688 and #689)
