### ISSUE TITLE
correct text in email that goes out to reviewers / remove links

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#679]
> Dear Laura Wimbiscus,
> 
> You have been asked to review the submission "Bananas for everyone," an application to the grant World Changing Moon Shot Ideas in Competitions - Staging.
> 
> By clicking the link above you can review or opt out of reviewing this submission.
> 
> Thank you.

This text says "by clicking the link above" but there are actually 3 links to click: the submission, the grant and Competitions the site. 

Jeff had another question, which was where to download the submission files. He said: "It’s not intuitive to me that you click on the Submission Title to get to the screen where you download the files. It won’t matter after you’ve done it once, but just an FYI."

I'm not exactly sure what to make of this, but one solution would be to limit the links in the reviewer email to just the review. That way they'd be forced to click on only one thing which would take them to what I think is a pretty clear page--you can read the submission, review the submission, or opt out. If you choose to review it, you can get to the RFA, which I think was the point of putting that link in the email. 

@jseraf , @mattbaumann1 , what do you think?

**Comment by jseraf** [comment]
@lmkw Something like this?

> You have been asked to review the following submission to [link = Grant Name]:
> 
> By clicking the submission title below, you can review or opt out of reviewing this submission.
> "[link = Submission Title]," submitted by [Applicant Full Name] 
> 
> [Maybe include person who assigned the review info in case there are questions?]
> [Maybe a link to the reviewers MyReviews page?]
> 
> Thank you.

**Comment by lmkw** [comment]
I think if we put the link to the grant in there, they will scan the email and click on that. If you think it's worth putting the grant name in, I would not make it a link.

> You have been asked by [assigner name] to review the following submission: "[link = Submission Title]" for the [grant name].
> 
> By clicking on the submission title above, you can review or opt out of reviewing. 

Thank you

**Comment by lmkw** [comment]
looks good
