### ISSUE TITLE
unable to log out

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#690]
When I try to log out from staging, in Firefox, Safari or Chrome, I get this message:

We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

Try the homepage to see a list of current grants.

If I exit the browser and then re-enter, it has logged me off

**Comment by jseraf** [comment]
Happening on staging and production.

Edited from the staging log:
`I, INFO -- : [11aec669-3699-4b77-907c-924d05aa355d] Started DELETE "/users/sign_out" for xxx.xxx.xxx.xx at 2020-11-16 16:06:53 -0600
I, INFO -- : [11aec669-3699-4b77-907c-924d05aa355d] Processing by SamlSessionsController#destroy as HTML
I, INFO -- : [11aec669-3699-4b77-907c-924d05aa355d]   Parameters: {"authenticity_token"=>"[...]=="}
D, [2020-11-16T16:06:53.950136 #8980] DEBUG -- : [11aec669-3699-4b77-907c-924d05aa355d]   SamlUser Load (1.7ms)  SELECT "users".* FROM "users" WHERE "users"."type" = $1 AND "users"."id" = $2 ORDER BY "users"."id" ASC LIMIT $3  [["type", "SamlUser"], ["id", x], ["LIMIT", 1]]
I, INFO -- : [11aec669-3699-4b77-907c-924d05aa355d] Completed 500 Internal Server Error in 5ms (ActiveRecord: 1.7ms | Allocations: 792)
F,  FATAL -- : [11aec669-3699-4b77-907c-924d05aa355d]
[11aec669-3699-4b77-907c-924d05aa355d] ArgumentError (wrong number of arguments (given 1, expected 0)):
[11aec669-3699-4b77-907c-924d05aa355d]
[11aec669-3699-4b77-907c-924d05aa355d] app/controllers/saml_sessions_controller.rb:15:in `set_saml_session_index_on_current_user'`

**Comment by mattbaumann1** [comment]
@Simon-Bradley, I don't see your account in our system? It seems like you are referring to Github. Was this intended for the NU Competitions system?

**Comment by Simon-Bradley** [comment]
It's github I can't logout off. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
