### ISSUE TITLE
update devise_saml_authenticatable gem

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#698]
We are still on 1.6.1 of devise_saml_authenticatable and this may cause problems given our configurations. 

https://github.com/apokalipto/devise_saml_authenticatable/issues/183

**Comment by jseraf** [comment]
> DEPRECATION WARNING: SourceAnnotationExtractor is deprecated! Use Rails::SourceAnnotationExtractor instead. (called from <top (required)> at /Users/jds021/workspace/competitions/config/environment.rb:7)
DEPRECATION WARNING: Initialization autoloaded the constants DeviseSamlAuthenticatable::CompetitionsIdpEntityIdReader and DeviseSamlAuthenticatable::CompetitionsAttributeMapResolver.
>
> Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
>
> Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload DeviseSamlAuthenticatable::CompetitionsIdpEntityIdReader, for example,
the expected changes won't be reflected in that stale Class object.
>
> These autoloaded constants have been unloaded.
>
> Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at /Users/jds021/workspace/competitions/config/environment.rb:7)
