### ISSUE TITLE
talk to Keith & Phil about panel settings

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#715]
Keith (and Rich) – thanks for asking. I don’t want panelists second-guessing reviewer’s comments before the panel meets. For me, this would create a bad precedent. We encourage debate and second-guessing during the panel meeting, because it’s open and equitable debate (all can participate). What I want to avoid is a shadow review process that undermines the fairness and confidentiality of the process. Make sense? Phil

**Comment by jseraf** [comment]
related to #706 

@lmkw - Should there be a "hide reviews" option for the panel so that reviewers do not have access to all reviews and reviewer comments during the panel? If so, reviewers would be able to see all reviewed submissions and their respective overall and composite score.

**Comment by lmkw** [comment]
Per Keith: 
He wants to be able to hide the reviewer comments only, keeping all application materials and scores visible. During the period when the full panel has access to the submitted materials.

But, I think we should make this one checkbox for hide comments, one checkbox for hide scores in case there is someone who wants to hide everything
