### ISSUE TITLE
Add test env saml idp

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#717]
Useful into for #696 and first time log in for #253

**Comment by jseraf** [comment]
Work based on similar functionality in devise_saml_authenticatable done 4a6e66b

**Comment by mattbaumann1** [comment]
There seems to be a handful of ways to approach this problem. 
We worked through the Docker solution found below. Unfortunately it looks like there still might be some issues  with the docker container solution.
https://hub.docker.com/r/kristophjunge/test-saml-idp

This repo hasn't been updated in 3 years and there seems to be a documented issue with the logout. 
https://github.com/kristophjunge/docker-test-saml-idp/issues/29

Documentation of this attempt can be found in the following wiki
https://github.com/NUARIG/competitions/wiki/Installation-and-configuration-of-test-saml-idp

**Comment by mattbaumann1** [comment]
If we are going to continue to explore this avenue. I think it will mean looking into one of the following gems.

https://github.com/lawrencepit/ruby-saml-idp

https://github.com/mcguinness/saml-idp

**Comment by mattbaumann1** [comment]
Logout seems to be working on this after setting the SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE. I have changed the wiki to reflect this.
