### ISSUE TITLE
Validation logic check for Open date and Publish date

### ISSUE THREAD

**Issue by nutodd** [NUARIG/competitions#723]
Can 'Open Date' be allowed to be the same as 'Publish Date'? 
Currently I cannot set publish date and open date to be the same date. EDW testing resulted in the question. It's not particularly burdensome to be forced to set the open date at least one day later than the publish date, just felt odd that it was restricted.

**Comment by mattbaumann1** [comment]
Can't reproduce. Logic is appropriate for today or after and publish date should not affect open date.
