### ISSUE TITLE
Investigate allow submission review during open submission period

### ISSUE THREAD

**Issue by nutodd** [NUARIG/competitions#724]
EDW has a use case where they need to review submissions throughout the span of the <submission open/close dates> Current requirement where <REVIEW OPEN DATE must be greater than SUBMISSION CLOSE DATE> does not work well/at all for them.

EDW pilot award program allows researchers to apply for funding throughout a given fiscal year. As a reviewer I need to be able to review a given submission while submission period continues to be open for the rest of the year/future applicants.

**Comment by lmkw** [comment]
Laura tested, you can run reviews concurrent to submission open dates, effectively allowing rolling submissions
