### ISSUE TITLE
Login link should keep requested page for redirect

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#727]
Login link in header should track user's page and redirect back to that page.

Current behavior: Home page > Grant RFA > Login > Home page
Desired behavior: Home page > Grant RFA > Login > Grant RFA

**Comment by mattbaumann1** [comment]
https://github.com/heartcombo/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update
