### ISSUE TITLE
Notifications for grant creator requests

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#728]

**Comment by lmkw** [comment]
Need notifications to go to Competitions email address

**Comment by mattbaumann1** [comment]
@lmkw What wording do you want in the email for users? 
Right now I have something generic like the following. The code areas are links out to the application. 

There are grant creator requests in need of review. 
A grant creator request was generated by the following user. 
`D.J. Bonebrake`
The full list of pending grant creator requests can be found at the following link. `http://localhost:3000/grant_creator_requests
`
Thank you.
