### ISSUE TITLE
test 1.6

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#732]

**Comment by jseraf** [comment]
@lmkw this release has been deployed. Changes include:
- #253 Invite to be a reviewer workflow (search by email, link to invite in banner, invite email, new user added as reviewer on sign in -- saml and registered user) 
- #372 Grant Permission searches by autocompleted email search

**Comment by jseraf** [comment]
Also includes #663 - Fix form layout on grant permission tab

**Comment by lmkw** [comment]
All looks well to me
