### ISSUE TITLE
Test release 1.7

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#746]
Release 1.7 adds the submissions excel export to the submissions tab under the grant edit menu. 
#667 

When testing, please consider:
- different browsers (chrome/firefox/safari) 
- file types (pdf/docx)
- multiple question sections

NOTE: changes made in #619 mean that older file uploads will break -- may want to set up a new competition with multiple file uploads across different question sections.

**Comment by lmkw** [comment]
#667 looks good, in chrome firefox and safari, with pdfs and with .docs.  The only thing I question is why we worded this "Save all Submissions" (we also said "Save all Reviews"). I think Export is clearer? Can't recall why we made that decision

**Comment by mattbaumann1** [comment]
Asked 4 different people (Emily, Keith, Eleanor and Adam) and the consensus was this should be called "Export All Submissions"

This was done on a commit on the 1.7 release branch.
