### ISSUE TITLE
Software license

### ISSUE THREAD

**Issue by william-shuman** [NUARIG/competitions#750]
How is this software licensed?  I couldn't locate any references in the source code.

**Comment by mattbaumann1** [comment]
https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by mattbaumann1** [comment]
From @mgurley,
However, my assumption was that it should always be MIT license with NU as the  Copyright (c) 2019 Northwestern Applied Research Informatics Group.  Git supplies a boilerplate MIT license that you only need to customize with an attribution.  And you just then commit it in the root of the repo.

@lmkw and @firaswehbe,
Is this the solution that we want to go with for Competitions?

**Comment by lmkw** [comment]
@mattbaumann1, yes

**Comment by mattbaumann1** [comment]
@william-shuman , license has been added. 
https://github.com/NUARIG/competitions/commit/8fbc150ee3695f0179d871218107cf88d01cd020
