### ISSUE TITLE
Requirements gathering for NUCATS evaluation reports

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#754]
For purposes of grant renewal, reports for Keith and Pearl
Matt and John will follow up with Pearl to see what she needs, what they should build
Rake tasks, etc

**Comment by mattbaumann1** [comment]
Meeting with Pearl took place today. She will get back to us after checking with Keith as to the information that is needed in these reports. The issue will stay open but we are waiting on Pearl's information to proceed.

**Comment by mattbaumann1** [comment]
Keith's meeting with Pearl was canceled. After discussing with Pearl further, it was agreed that we would rebuild the new reports based on the specs of the old reports in NITRO Competitions.

**Comment by mattbaumann1** [comment]
Thew work will be done in #773
