### ISSUE TITLE
Explore exception notifications 

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#755]
Implement something like Sentry (NOTIS uses)?
Something to let us know when something goes wrong for the users so we needn't rely on them to communicate with us
Talk to pods

**Comment by mattbaumann1** [comment]
I discussed this with @jpatel on 2/3/2021. They use Sentry for StudyTracker. However, she would not necessarily encourage us to spend time on implementing it. She instead encouraged me to explore CI in GitHub with our limited time.

**Comment by mattbaumann1** [comment]
https://gorails.com/episodes/github-actions-continuous-integration-ruby-on-rails

**Comment by lmkw** [comment]
Jalpa doesn't think it's more useful than a generic exception mailer. Would prioritize spending time mitigating errors rather than creating mechanism for detailed error emails. But we think we need *some* kind of notification of error, we missed a user being unable to upload files for a grant over a weekend.

**Comment by jpatel** [comment]
@lmkw:  I assume that competitions already have generic exception handling. If competitions do not have exception handling at all, then it should have one for sure.

I was suggesting CI build over sentry, under the assumption of that exception handling is already exist. Sentry is just another way of exception handling.

**Comment by jpatel** [comment]
"But we think we need some kind of notification of error, we missed a user being unable to upload files for a grant over a weekend." this could be bug in process, which should have raise error. If it did not, then process should raise error! if process does not raise error at all, no generic exception handling or sentry would able to send any notification.

**Comment by mattbaumann1** [comment]
add exception_notification gem for the simplest level of exception notification. This can be modified or changed in the future as needs require. 

https://github.com/smartinez87/exception_notification

**Comment by mattbaumann1** [comment]
The following code needs to be added to each of the server environment files when this is deployed. 

`  config.middleware.use ExceptionNotification::Rack,
    email: {
      email_prefix: "[#{Rails.env}][#{COMPETITIONS_CONFIG[:application_name]}] ",
      sender_address: COMPETITIONS_CONFIG[:contact_email],
      exception_recipients: COMPETITIONS_CONFIG[:mailer][:email]
    }`
