### ISSUE TITLE
Allow admins to opt-in to receiving notification when a submission is submitted

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#756]
Request from Dan Schneider, would like to receive an email when a submission is submitted because his competition is a rolling one and he may not remember to check Competitions to see new submissions

**Comment by lmkw** [comment]
Let's put this on the Permissions tab since it is grant-related

**Comment by mattbaumann1** [comment]
Add to the permission edit page above the update button.

**Comment by mattbaumann1** [comment]
This functionality was added to the edit screen for grant permissions. It was not added to the index page.
