### ISSUE TITLE
create release notes file

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#761]
Create a release notes that tracks the tickets/commits in each release in a human readable format.

**Comment by mattbaumann1** [comment]
Thinking about this issue. There are a couple of options.

- a file checked into the repo for release notes? 
- adding list of changes to GitHub release notes. 
     (ex. https://github.com/NUARIG/competitions/releases/1.7)

**Comment by lmkw** [comment]
Decision: Flat haml page on Competitions with date and list of release notes (issue names only), put under Help dropdown and link under version number
