### ISSUE TITLE
Add reporting mechanisms

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#773]
Request to add something that recreates existing monthly and quarterly reports used by NUCATS.

see #754 .

**Comment by jseraf** [comment]
Pearl needs the following info grants -- dates (open/close), count of submissions (complete/draft), count of reviewed submissions. Needed these on a monthly or quarterly basis.

Possible solutions Matt and I discussed:
- admin dashboard with configurable searches
- rake tasks w/ mailers
- back end selects/tasks

Related to #272
