### ISSUE TITLE
Test release/1.9

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#783]
Find a list of new features and associated tickets on the release notes page. 
http://competitions-staging.fsm.northwestern.edu/documentation/release

**Comment by lmkw** [comment]
@mattbaumann1  this looks fantastic. I especially like the release notes page!
Is there any practical way I can test the exception notifications?

**Comment by mattbaumann1** [comment]
@lmkw @jseraf 
Can this release branch be released to production?

**Comment by lmkw** [comment]
Yes please!
