### ISSUE TITLE
Add notification checkbox on create permissions

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#793]
Add some text on Permissions tab to let people know they can be notified of grant submissions.

**Comment by jseraf** [comment]
Could also add a link on the Submissions page

**Comment by lmkw** [comment]
Add text on Permissions tab to let people know receiving notifications is an option
and/or
Add boolean of receive notifications on Create permissions view

**Comment by mattbaumann1** [comment]
There is a checkbox on the edit view of the grant permissions for notifications. This checkbox should be included on the update screen also.
