### ISSUE TITLE
move Review Guidance from Overview to Review Criteria tab

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#817]

**Comment by mattbaumann1** [comment]
@lmkw, Here is what the new location for the review guidance looks like on the review criteria tab. What are your opinions? Should that tab be renamed?
<img width="1305" alt="Screen Shot 2021-06-01 at 8 59 56 AM" src="https://user-images.githubusercontent.com/10729154/120336439-f62ed480-c2b7-11eb-894c-c927863b5b2b.png">

**Comment by mattbaumann1** [comment]
This also changed the overview to the following. 
<img width="766" alt="Screen Shot 2021-06-01 at 9 20 58 AM" src="https://user-images.githubusercontent.com/10729154/120339437-bd442f00-c2ba-11eb-9aef-8a3045ee0041.png">

**Comment by lmkw** [comment]
Good point @mattbaumann1 . It's kind of like a Review Form now?
