### ISSUE TITLE
Invite someone to be an applicant on a grant

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#837]
If someone is not already in Competitions, we need a way for a submitter to invite them so that submitter can apply on their behalf (i.e. list their name as an applicant).

This should function similarly to the reviewer invite and its link to grants. Here it will be an applicant on a submission. 
We will need to check for any pending invitations on user creation. 

Does it make sense to generalize the reviewer invitation into a general invitation and then use STI for the different types of invitations?

**Comment by lmkw** [comment]
dependent on #838

**Comment by mattbaumann1** [comment]
relates to #828
