### ISSUE TITLE
Update routes

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#85]
Does FormBuilder need its own namespace within the application? Should it be nested under the grant?

**Comment by firaswehbe** [comment]
If I understand this question correctly, I suppose a submission namespace would be a good thing to have. I think the unique submission ID (submission form ID) being a useful identifier throughout. I see us exposing the explicit submission ID to the controllers and routes for useful actions (e.g. for admins to go and update or delete a submission, or to give a status page that's visible to the owner of the submission etc...)

**Comment by firaswehbe** [comment]
I just saw #86 and noticed you are calling the submission form model `GrantSubmission`. The ID I was referring to in my previous comments would the the unique id associated with that model.

**Comment by firaswehbe** [comment]
I'm withdrawing my comments based on our in person conversation just now.
