### ISSUE TITLE
Fix formatting of cards

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#880]
It looks like the cards on the home page need changes to truncate the titles after a certain length and that the RFA link needs less padding. 
<img width="491" alt="Screen Shot 2021-11-04 at 11 45 18 AM" src="https://user-images.githubusercontent.com/10729154/140382632-b3580219-9d9d-4a08-a84a-2c1504c032f7.png">

**Comment by lmkw** [comment]
@jseraf  is this done?

**Comment by jseraf** [comment]
@lmkw there's an open/linked PR waiting review/merge

**Comment by mattbaumann1** [comment]
There is a limit of 255 characters for a grant name.
