### ISSUE TITLE
Disambiguate logging in via NetID vs via email

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#883]
To the Administrators of the “Competitions” website,

I am the Director of Global Initiatives in the McCormick School of Engineering and a full Professor of Electrical and Computer Engineering, and I have recently created a funding opportunity posted on “Competitions”
that McCormick and Weinberg faculty are eligible to apply for.

However, mnyself (initially) and other faculty have suffered a series of frustrations in trying to log into the “Competitions” website, and I fear that the log-in page is not as intuitive as the designers
may have intended.

I have tried to summarize the logic of how a first-time viewer sees this log-in page so that you can make some modifications, such as the ones I recommend at the end of this email, so that the “Competitions”
site gets the widespread recognition and reputation for ease-of-use that it deserves:

1) When you log in, the bold face messages says “Log in WITH YOUR INSTITUTIONAL ACCOUNT with NetID, ENTER YOUR ACCOUNT DETAILS” so the natural tendency is to enter your netID in the top yellow box, and password
in the bottom yellow box.  The idea that the purple box containing the phrase “with NetID” in the sentence “Log in with NetID” is actually a button that you should press is not obvious.  One reason is the almost transparently light font color for the word
“OR”.

2) When you make a mistake and accidentally try logging into the account with your Net ID in the box that says ENTER YOUR ACCOUNT DETAILS, then you get the 2nd screen shot below which never gives
you a 2nd chance to return to the purple “With NetID” box. Where the Net ID login button used to be (which you thought was a message) is now a *message* which is *not* a button, but which says “invalid email or password.”

Here are some possible recommendations, anyone of which should solve the problem:

1) have “with NetID” be in blue underline so that everyone recognizes it is a hypertext link

2) Instead of having a purple box “With NetID” and yellow text windows below under “Enter your account details” have two purple boxes, one labeled “With Net ID” and another labeled “With Your Account Name.” 
And then, just as the “With NetID” is a button which goes to an intermediary page to enter net ID and password, have the “With Your Account Name” go to an intermediary page to enter email and password.

3) make the text “OR” which is currently the lightest, barely visible text on the page be BOLD FACE with a font as large and thick as the “Log in” font.

4) make the “error” page include not ONLY the message “invalid email or password.” but also the purple box that once again gives the opportunity to “Log in with NetID”.

5) on the “with NetID” button add the words “(click here)” and precede with the words “Log in” so it reads “Log in with NetID (click here)”.

This is of interest to me because I wish to be able to recommend this site to faculty so they can apply for the McCormick Faculty Networking Grant that I have recently created, but every time I send this link,
I feel I have to send an extra disclaimer: “Be warned that the purple box that looks like part of the text is actually a button that you have to click on in order to proceed, and whatever you do, don’t enter any account information in the box that says ‘Enter
your Account details’ because then you will be stuck in an infinite loop and you will never be able to log in properly until you close the webpage and start over again.’

I would rather save myself the effort, and save my colleagues the confusion.

Thanks for reading this, and I hope some action can be taken so that this website leads not to frustration, but accolades from all around.

**Comment by jseraf** [comment]
Additional work in #897
