### ISSUE TITLE
Test release version 1.15

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#888]
- [ ] Account for long grant titles in CSS. #880
- [ ] Clarify the login page with better error messages and links. #885

**Comment by mattbaumann1** [comment]
This was carried out by Keith and I.

**Comment by lmkw** [comment]
For #880, what's the maximum length of a title?
![Screen Shot 2022-01-28 at 4 43 40 PM](https://user-images.githubusercontent.com/12861678/151631970-8ee042c0-b5ae-4846-af58-14a20aceea27.png)
