### ISSUE TITLE
Should there be additional domains added to our configuration of SAML domains?

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#890]
Should we add additional domains to the SAML domains configuration? 
Currently we only block northwestern.edu.
Should we also force other domains to login with their NetID? Such as nm.org, luriechildrens.org, etc.
What should those blocked domains include?
Plan for a migration of the old users from RegisteredUsers to SamlUsers.

**Comment by lmkw** [comment]
Let's ask Keith

**Comment by lmkw** [comment]
SRA Lab: "To answer your question, most applicants to our grants will not have NetIDs. The Catalyst Grant is offered to all employees at SRAlab, so even housekeeping may apply. Thus, many if not most will not have an NU affiliation or net ID. Applicants to the C-STAR grants will be almost all outside the NU/Lurie/SRAlab systems. This grant is offered nationally. Does this help?"
