### ISSUE TITLE
Include link to the review form in the email sent to reviewers

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#941]

**Comment by lmkw** [comment]
Dear [reviewer name]

You have been asked by [review assigner] to review the following submission: 
[submission name ](link to submission)
by [submitter]
for [grant name]

The deadline for your review is [date review must be complete].

Review or opt out of reviewing here (link to the page where you can review or opt out)

Thank you.

**Comment by jseraf** [comment]
@lmkw might be easier to link to the review page directly, as that page contains a link to the submission

**Comment by lmkw** [comment]
@jseraf i wanted to link to this page, because here you can see the submission, opt out, or continue to the review form. is that what you meant or do you mean the review form?
<img width="1090" alt="Screen Shot 2022-06-16 at 12 59 08 PM" src="https://user-images.githubusercontent.com/12861678/174135977-617be0a6-5861-4afc-a11e-7d781e179039.png">
