### ISSUE TITLE
cannot run develop due to application.js missing. 

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#945]
Sprockets::Rails::Helper::AssetNotFound at /
The asset "application.js" is not present in the asset pipeline.

We are unable to run develop because the application.js file is not building.

**Comment by mattbaumann1** [comment]
@jseraf ran the following and it fixed this issue. 
`rails stimulus:manifest:update`

**Comment by jseraf** [comment]
Closed in 42a40ba

**Comment by mattbaumann1** [comment]
While trying to deploy the fix of this issue, we ran into issues with yarn installation on the server. We created the branch task/yarn-install-deployment-issues-945 to deal with this. We are currently waiting on server changes before this ticket can proceed.

**Comment by mattbaumann1** [comment]
Relates to #946

**Comment by mattbaumann1** [comment]
merged directly into develop
