### ISSUE TITLE
Submission index pages show no applicant name 

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#951]
While running specs, I saw some instances where an Applicant name did not appear in the column.

e.g. Run `spec/system/panels` or `grant_submissions`

**Comment by mattbaumann1** [comment]
@jseraf was this fixed when you built the JS file locally?

**Comment by jseraf** [comment]
@mattbaumann1 close if you can't recreate in the specs i mentioned in the summary above

**Comment by jseraf** [comment]
Closing. Will re-open or create a new ticket if encountered again
