### ISSUE TITLE
remove invited reviewers

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#958]
"Attached is a screen grab. The issue is that I don't want to send a
reminder to all of these email addresses. I only want to send one to
g-revivo. However, if I select "Send Reminder to
Invited Reviewers," a message is sent to the full list of those who
did not confirm. Can you remove the following emails from the
invitation list: eroth, mrafferty, and
 grevivo?"

Update -- see comments.

**Comment by jseraf** [comment]
Related to #911 

Updated ticket to remove screenshot and email addresses.
