### ISSUE TITLE
explore redis server on staging. 

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#959]
Deployment was blocked because of action cable, but Hotwire will need this. This requires a redis server. Should this be a separate server or on the same server? We will walk through this on staging and figure out the process for production. 

These lines were commented for now to allow for deployment, but they should be uncommented, so these  lines 5,7, and 29 when ActionCable is ready to be restored.

**Comment by mattbaumann1** [comment]
Talked with Jalpa about this and suggested the following process.

- [ ] Apply to FSMIT for server
- [ ] update configuration file in application (once allocated)
- [ ] Potentially will need to update deploy script

Jalpa noted that NOTIS uses a redis server currently.

**Comment by mattbaumann1** [comment]
redis server requested from FSMIT

**Comment by mattbaumann1** [comment]
redis has been added to the staging server but has not been added to the production server. See email for details on redis.

**Comment by jseraf** [comment]
@mattbaumann1 and i are meeting on 9/1 to figure this out.
