### ISSUE TITLE
Test release version 1.17

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#966]
Test new version of Competitions.
A list of changes can be found in the release notes of the application. 

After #965

**Comment by jseraf** [comment]
[] - Add ability manage reviewer invitations. [#911](https://github.com/NUARIG/competitions/issues/911)
[] - Specify language in html tags. [#196](https://github.com/NUARIG/competitions/issues/196)
[] - Change text for reviewer email. [#941](https://github.com/NUARIG/competitions/issues/941)
[] - Clean up banner and grant reviewer views. [#935](https://github.com/NUARIG/competitions/issues/935)
[] - Add notifications column to the index of grant permissions. [#792](https://github.com/NUARIG/competitions/issues/792)
[] - Add checkbox for submission notifications to new grant permissions. [#793](https://github.com/NUARIG/competitions/issues/793)
[] - Cache visible system banners and include on all pages. [#235](https://github.com/NUARIG/competitions/issues/235)
[] - Fix signout issue. [#964](https://github.com/NUARIG/competitions/issues/964)
[x] - Fix deployment issues. [#946](https://github.com/NUARIG/competitions/issues/946)
[] - Remove logged in saml user access to registered user pages. [#602](https://github.com/NUARIG/competitions/issues/602)
[x] - Fix failing specs. [#936](https://github.com/NUARIG/competitions/issues/936), [#947](https://github.com/NUARIG/competitions/issues/947), [#957](https://github.com/NUARIG/competitions/issues/957)
[x] - Add jsbundling for handling javascript. [#931](https://github.com/NUARIG/competitions/issues/931)
[x] - Add turbo-rails gem. [#954](https://github.com/NUARIG/competitions/issues/954)
[x] - Upgrade devise gem. [#964](https://github.com/NUARIG/competitions/issues/964)
[x] - Upgrade devise_saml_authenticatable gem. [#964](https://github.com/NUARIG/competitions/issues/964)
[x] - Bump nokogiri 1.13.6. [#939](https://github.com/NUARIG/competitions/issues/939)
[x] - Bump rack 2.2.3.1. [#948](https://github.com/NUARIG/competitions/issues/948)
[x] - bump rails-html-sanitizer to 1.4.3 #952 [#922](https://github.com/NUARIG/competitions/issues/922)
