### ISSUE TITLE
Sending reminders to only assigned reviewers

### ISSUE THREAD

**Issue by rsd308** [NUARIG/competitions#969]
hello! when trying to send reminders to reviewers, the email goes out to all invited reviewers and not just the assigned reviewers.
Furthermore, there doesn't seem to be a way to remove reviewers from invited list. thank you

**Comment by jseraf** [comment]
@rsd308 Some of this will be addressed with the next production release of the application. I'll follow up via email with some other specifics. Thanks.

**Comment by jseraf** [comment]
@rsd308 The changes were deployed. Please re-open if you have any additional issues w/ this.
