### ISSUE TITLE
Staging testing

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#990]
Deployed most recent changes, including:
[X] - #774 - Grant contact option added to permissions. Contact(s) info appears on Grant display when has been assigned.
[X] - #984 - Change Grant Permission  form drop-down to use Tom Select library, removing Select2
[X] - Inline editing of Grant Permissions using Turbo/Hotwire
[X] - Turbo affected how forms are submitted across the site. Recommend testing across the site (submissions, reviews, grant forms, etc).

**Comment by lmkw** [comment]
Looks good
