### ISSUE TITLE
Grants with expired submission dates should not show an Apply Now button

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#994]
One of the grant admins sent out an email with a call for letters of intent that accidentally contained the link to the prior year's grant. As far as I can tell, as long as you have the URL, you can get to old grants and still apply to them. I thought the Apply Now button disappeared once the grant submission date had passed. Can we make sure that button does not appear when the grant submission date has passed?

**Comment by lmkw** [comment]
I was able to test in production creating another account, and the Apply Now button does not show. However, you get the error message You are not authorized to perform this action
Any chance that could be changed to "This grant is no longer accepting submissions"?

**Comment by jseraf** [comment]
Show/hide of the "Apply now" is based on permissions or whether the grant is accepting submissions. See:
https://github.com/NUARIG/competitions/blob/develop/app/views/grants/_apply_button.html.haml#L1
https://github.com/NUARIG/competitions/blob/develop/app/models/grant.rb#L162

**Comment by jseraf** [comment]
Closing.
